name: Check pull request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-build:
    name: Check ubild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install deps
        run: npm i

      - name: build
        run: npm run build:crab
