name: Check Subql

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-subql:
    name: Check subql
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - name: feemarket
            chain: darwinia
          - name: bridger
            chain: darwinia
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        working-directory: subql
        run: |
          yarn install
          yarn boot
          yarn build:common

      - name: Check subql
        working-directory: subql
        run: yarn build:${{ matrix.project.name }} -- ${{ matrix.project.chain }}

  check-subgraph:
    name: Check subgraph
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - name: ethv2
            chain: darwinia
          - name: feemarket
            chain: ethereum
          - name: feemarket
            chain: darwinia
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Check subgraph
        run: |
          cd thegraph/${{ matrix.project.name }}
          yarn install
          yarn codegen -- subgraph-${{ matrix.project.chain }}.yaml
          yarn build -- subgraph-${{ matrix.project.chain }}.yaml
