name: Check pull request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-subql:
    name: Check subql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.1

      - name: install deps
        working-directory: subql
        run: yarn install

      - name: build subql
        working-directory: subql
        run: yarn build:crab
