name: Check pull request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-subql:
    name: Check subql
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - apps
          - bridger
          - mmr
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install deps
        working-directory: subql
        run: yarn install

      - name: build subql
        working-directory: subql
        if: matrix.project == 'apps'
        run: npm run build:${{ matrix.project }} -- darwinia

      - name: build subql
        working-directory: subql
        if: matrix.project == 'bridger'
        run: npm run build:${{ matrix.project }} -- darwinia

      - name: build subql
        working-directory: subql
        if: matrix.project == 'mmr'
        run: npm run build:${{ matrix.project }} -- darwinia
