name: Release

#on:
#  push:
#    tags:
#      - "v*"

on:
  pull_request:

env:
  SUBQUERY_ORG: fewensa

jobs:
  deploy-subql:
    name: Deploy subql
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain:
          - pangolin
          - pangoro
          - darwinia
          - crab
          - pangolin-parachain
          - crab-parachain
          - kusama
          - rococo
    steps:
      - uses: trstringer/manual-approval@v1
        timeout-minutes: 15
        with:
          secret: ${{ github.TOKEN }}
          approvers: fewensa,HackFisher,JayJay1024,sxlwar
          minimum-approvals: 1
          issue-title: "Deploy subql for production mode about chain ${{ matrix.chain }}?"

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install deps
        working-directory: subql
        run: yarn install

      - name: build subql
        working-directory: subql
        run: npm run build:${{ matrix.chain }}

      - name: publish subql
        working-directory: subql
        run: npm run publish -- ${{ matrix.chain }}

      - name: deploy subql
        working-directory: subql
        run: |
          echo npx subql deployment:deploy -d \
            --type primary \
            --org ${{ env.SUBQUERY_ORG }} \
            --projectName ${{ matrix.chain }} \
            --endpoint https://pangolin-rpc.darwinia.network \
            --ipfsCID 12345
