name: Release

#on:
#  push:
#    tags:
#      - "v*"

on:
  pull_request:

jobs:
  deploy-subql:
    name: Deploy subql
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: fewensa

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install deps
        working-directory: subql
        run: yarn install

      - name: build subql
        working-directory: subql
        run: yarn build:crab
