## todo: update ci
name: Release Subgraph

on:
  workflow_dispatch:

jobs:
  package-thegraph:
    name: Package thegraph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2




#  thegraph-ethereum:
#    name: Subgraph Ethereum like v1
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        chain: [ethereum, ropsten]
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '16'
#      - name: Deploy
#        working-directory: thegraph/ethv1
#        run: |
#          npm i
#          npm run codegen -- subgraph-${{ matrix.chain }}.yaml
#          npm run build -- subgraph-${{ matrix.chain }}.yaml
#          npm run deploy -- --access-token ${{ secrets.THEGRAPH_TOKEN_PROD }} \
#            darwinia-network/bridge-${{ matrix.chain }} \
#            subgraph-${{ matrix.chain }}.yaml
