name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  package-subql:
    name: Deploy subql
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - apps
          - bridger
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}
      - uses: benjlevesque/short-sha@v1.2
      - uses: olegtarasov/get-tag@v2.1

      - name: install deps
        working-directory: subql
        run: |
          npm i
          npx lerna bootstrap

      - name: build image
        working-directory: subql
        run: |
          BASE_PATH=$(pwd)
          PROJECT="${{ matrix.project }}"
          REPO_NAME="${{ github.repository }}"
          FILE_PROJECt_CHAIN_MAPPING=${BASE_PATH}/../.maintain/subql-project-chain.json
          CHAINS=$(jq -r ".${PROJECT} | .[]" $FILE_PROJECt_CHAIN_MAPPING)
          for CHAIN in ${CHAINS}; do
            echo ''
            echo ''
            echo ''
            echo ''
            echo "====== Build ${PROJECT} for ${CHAIN} ======"
            cd ${BASE_PATH}/packages/${PROJECT}
            npm run build -- ${CHAIN}

            IMAGE_NAME_BASE=${{ env.DOCKER_REGISTRY }}/${REPO_NAME}/subql-${PROJECT}-${CHAIN}
            IMAGE_NAME_SHA=${IMAGE_NAME_BASE}:sha-${SHA}
            IMAGE_NAME_TAG=${IMAGE_NAME_BASE}:${GIT_TAG_NAME}
            echo "${IMAGE_NAME_SHA}" >> ${BASE_PATH}/images.txt
            docker build \
              -t ${IMAGE_NAME_SHA} \
              ${GIT_TAG_NAME:+-t $IMAGE_NAME_TAG} \
              -f ${BASE_PATH}/Dockerfile \
              .
            docker push ${IMAGE_NAME_SHA}
            if [ -n "${GIT_TAG_NAME}" ]; then
              echo "${IMAGE_NAME_TAG}" >> ${BASE_PATH}/images.txt
              docker push ${IMAGE_NAME_TAG}
            fi
          done

          OUTPUT_CONTENT=$(cat ${BASE_PATH}/images.txt)
          OUTPUT_CONTENT="${OUTPUT_CONTENT//'%'/'%25'}"
          OUTPUT_CONTENT="${OUTPUT_CONTENT//$'\n'/'%0A'}"
          OUTPUT_CONTENT="${OUTPUT_CONTENT//$'\r'/'%0D'}"
          echo ''
          echo "::set-output name=OUTPUT_CONTENT::$OUTPUT_CONTENT"
