name: Release

on:
  push:
    tags:
      - "v*"
  pull_request:


jobs:
  package-subql:
    name: Deploy subql
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - apps
          - bridger
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: install deps
        working-directory: subql
        run: |
          npm i
          npx lerna bootstrap

      - name: deploy project
        working-directory: subql
        run: |
          BASE_PATH=$(pwd)
          PROJECT="${{ matrix.project }}"
          FILE_PROJECt_CHAIN_MAPPING=${BASE_PATH}/../.maintain/subql-project-chain.json
          CHAINS=$(jq -r ".${PROJECT} | .[]" $FILE_PROJECt_CHAIN_MAPPING)
          for CHAIN in ${CHAINS}; do
            echo docker build .
          done

